version: "2"
linters:
  enable:
    - gosec
    - revive
  settings:
    gosec:
      excludes:
        - G104
    revive:
      rules:
        - name: var-naming
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
